apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
  labels:
    component: fluentd
data:
  elasticsearch_username: elastic
  elasticsearch_password: J7ZXwkyQ9wOOsBhKLMFr