apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: kibana-gateway
  namespace: kube-logging
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - sso.169.46.14.124.nip.io
      port:
        name: http
        number: 80
        protocol: HTTP