apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kube-logging
  labels:
    component: kibana
data:
  elasticsearch_username: elastic
  elasticsearch_password: J7ZXwkyQ9wOOsBhKLMFr